title: Francesca's Tech Blog
description: My thoughts on AI and Tech developments
author: Francesca Beaumont
email: francescambeaumont@gmail.com
url: https://francesssss.github.io/tech-blog
baseurl: /tech-blog

# Jekyll theme
remote_theme: wowthemesnet/mundana-jekyll-theme

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Pagination (optional)
paginate: 5
paginate_path: /page:num/
