title: Francesca's Tech Blog
description: My thoughts on AI and Tech developments
author: Francesca Beaumont
email: francescambeaumont@gmail.com
url: https://francesssss.github.io
baseurl: ""

# Jekyll theme
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Pagination (optional)
paginate: 5
paginate_path: /page:num/
